# models.py
# SmartStock AI - Pydantic Data Schemas
# These models define the API contract between backend and frontend

from pydantic import BaseModel, Field
from typing import List, Optional


class Citation(BaseModel):
    """
    Represents a verifiable source reference used in the agent's response.
    Citations ensure financial information can be traced back to official sources.
    """
    id: int = Field(
        description="Sequential citation number (e.g., 1, 2, 3)."
    )
    source_type: str = Field(
        description="Type of source: '10-Q', '10-K', 'News Article', 'SEC Form 4', 'Metric API'."
    )
    source_detail: str = Field(
        description="File name, article headline, link, or specific source snippet."
    )


class Metrics(BaseModel):
    """
    Represents a structured metric for rendering in comparison charts or event cards.
    The color_context provides UI hints for visual differentiation.
    """
    key: str = Field(
        description="The name of the metric (e.g., 'Max Drop', 'YoY Revenue Growth', 'P/E Ratio')."
    )
    value: str = Field(
        description="The numeric or categorical result (e.g., '-5.12%', '14.5B USD', 'Downgrade')."
    )
    color_context: Optional[str] = Field(
        default=None,
        description="A hint for the frontend styling: 'red', 'green', 'blue', or 'yellow'."
    )


class AgentResponse(BaseModel):
    """
    The complete structured response from the SmartStock AI agent.
    This model ensures all responses are validated before reaching the frontend.
    """
    synthesis: str = Field(
        description="The primary, conversational answer generated by the LLM with inline citation references."
    )
    metrics_snapshot: List[Metrics] = Field(
        description="Structured data for rendering comparison charts or event cards."
    )
    citations: List[Citation] = Field(
        description="The verifiable source references used for the answer."
    )


class QueryRequest(BaseModel):
    """
    Incoming query request from the frontend.
    """
    query: str = Field(
        description="The user's financial question or analysis request."
    )
    chat_id: str = Field(
        default="default-session",
        description="Session identifier for conversation continuity (future use)."
    )

